//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.13 at 11:41:18 AM PST 
//


package viskit.xsd.bindings.assembly;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the viskit.xsd.bindings.assembly package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ValueRange_QNAME = new QName("", "ValueRange");
    private final static QName _Statistics_QNAME = new QName("", "Statistics");
    private final static QName _Script_QNAME = new QName("", "Script");
    private final static QName _Log_QNAME = new QName("", "Log");
    private final static QName _Errors_QNAME = new QName("", "Errors");
    private final static QName _DoubleRange_QNAME = new QName("", "DoubleRange");
    private final static QName _IntegerRange_QNAME = new QName("", "IntegerRange");
    private final static QName _SampleStatistics_QNAME = new QName("", "SampleStatistics");
    private final static QName _IndexedSampleStatistics_QNAME = new QName("", "IndexedSampleStatistics");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: viskit.xsd.bindings.assembly
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValueRange }
     * 
     */
    public ValueRange createValueRange() {
        return new ValueRange();
    }

    /**
     * Create an instance of {@link SimkitAssembly }
     * 
     */
    public SimkitAssembly createSimkitAssembly() {
        return new SimkitAssembly();
    }

    /**
     * Create an instance of {@link Head }
     * 
     */
    public Head createHead() {
        return new Head();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link TerminalParameter }
     * 
     */
    public TerminalParameter createTerminalParameter() {
        return new TerminalParameter();
    }

    /**
     * Create an instance of {@link SimEntity }
     * 
     */
    public SimEntity createSimEntity() {
        return new SimEntity();
    }

    /**
     * Create an instance of {@link MultiParameter }
     * 
     */
    public MultiParameter createMultiParameter() {
        return new MultiParameter();
    }

    /**
     * Create an instance of {@link FactoryParameter }
     * 
     */
    public FactoryParameter createFactoryParameter() {
        return new FactoryParameter();
    }

    /**
     * Create an instance of {@link Coordinate }
     * 
     */
    public Coordinate createCoordinate() {
        return new Coordinate();
    }

    /**
     * Create an instance of {@link EventGraph }
     * 
     */
    public EventGraph createEventGraph() {
        return new EventGraph();
    }

    /**
     * Create an instance of {@link PropertyChangeListener }
     * 
     */
    public PropertyChangeListener createPropertyChangeListener() {
        return new PropertyChangeListener();
    }

    /**
     * Create an instance of {@link SimEventListenerConnection }
     * 
     */
    public SimEventListenerConnection createSimEventListenerConnection() {
        return new SimEventListenerConnection();
    }

    /**
     * Create an instance of {@link PropertyChangeListenerConnection }
     * 
     */
    public PropertyChangeListenerConnection createPropertyChangeListenerConnection() {
        return new PropertyChangeListenerConnection();
    }

    /**
     * Create an instance of {@link Adapter }
     * 
     */
    public Adapter createAdapter() {
        return new Adapter();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link Verbose }
     * 
     */
    public Verbose createVerbose() {
        return new Verbose();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link Experiment }
     * 
     */
    public Experiment createExperiment() {
        return new Experiment();
    }

    /**
     * Create an instance of {@link Sample }
     * 
     */
    public Sample createSample() {
        return new Sample();
    }

    /**
     * Create an instance of {@link DesignPoint }
     * 
     */
    public DesignPoint createDesignPoint() {
        return new DesignPoint();
    }

    /**
     * Create an instance of {@link Replication }
     * 
     */
    public Replication createReplication() {
        return new Replication();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link PropertyChange }
     * 
     */
    public PropertyChange createPropertyChange() {
        return new PropertyChange();
    }

    /**
     * Create an instance of {@link SampleStatistics }
     * 
     */
    public SampleStatistics createSampleStatistics() {
        return new SampleStatistics();
    }

    /**
     * Create an instance of {@link IndexedSampleStatistics }
     * 
     */
    public IndexedSampleStatistics createIndexedSampleStatistics() {
        return new IndexedSampleStatistics();
    }

    /**
     * Create an instance of {@link PasswordFile }
     * 
     */
    public PasswordFile createPasswordFile() {
        return new PasswordFile();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueRange }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ValueRange")
    public JAXBElement<ValueRange> createValueRange(ValueRange value) {
        return new JAXBElement<ValueRange>(_ValueRange_QNAME, ValueRange.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Statistics")
    public JAXBElement<Object> createStatistics(Object value) {
        return new JAXBElement<Object>(_Statistics_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Script")
    public JAXBElement<String> createScript(String value) {
        return new JAXBElement<String>(_Script_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Log")
    public JAXBElement<String> createLog(String value) {
        return new JAXBElement<String>(_Log_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Errors")
    public JAXBElement<String> createErrors(String value) {
        return new JAXBElement<String>(_Errors_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueRange }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DoubleRange", substitutionHeadNamespace = "", substitutionHeadName = "ValueRange")
    public JAXBElement<ValueRange> createDoubleRange(ValueRange value) {
        return new JAXBElement<ValueRange>(_DoubleRange_QNAME, ValueRange.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueRange }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IntegerRange", substitutionHeadNamespace = "", substitutionHeadName = "ValueRange")
    public JAXBElement<ValueRange> createIntegerRange(ValueRange value) {
        return new JAXBElement<ValueRange>(_IntegerRange_QNAME, ValueRange.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SampleStatistics }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SampleStatistics", substitutionHeadNamespace = "", substitutionHeadName = "Statistics")
    public JAXBElement<SampleStatistics> createSampleStatistics(SampleStatistics value) {
        return new JAXBElement<SampleStatistics>(_SampleStatistics_QNAME, SampleStatistics.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndexedSampleStatistics }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IndexedSampleStatistics", substitutionHeadNamespace = "", substitutionHeadName = "Statistics")
    public JAXBElement<IndexedSampleStatistics> createIndexedSampleStatistics(IndexedSampleStatistics value) {
        return new JAXBElement<IndexedSampleStatistics>(_IndexedSampleStatistics_QNAME, IndexedSampleStatistics.class, null, value);
    }

}
