//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.13 at 11:41:18 AM PST 
//


package viskit.xsd.bindings.assembly;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *       &lt;attribute name="mean" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="0.0" /&gt;
 *       &lt;attribute name="variance" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="0.0" /&gt;
 *       &lt;attribute name="standardDeviation" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="0.0" /&gt;
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="0" /&gt;
 *       &lt;attribute name="minObs" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="0.0" /&gt;
 *       &lt;attribute name="maxObs" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="0.0" /&gt;
 *       &lt;attribute name="samplingType" default="TALLY"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="TALLY"/&gt;
 *             &lt;enumeration value="TIME_VARYING"/&gt;
 *             &lt;enumeration value="LINEAR"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class SampleStatistics {

    @XmlAttribute(name = "name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String name;
    @XmlAttribute(name = "mean")
    @XmlSchemaType(name = "anySimpleType")
    protected String mean;
    @XmlAttribute(name = "variance")
    @XmlSchemaType(name = "anySimpleType")
    protected String variance;
    @XmlAttribute(name = "standardDeviation")
    @XmlSchemaType(name = "anySimpleType")
    protected String standardDeviation;
    @XmlAttribute(name = "count")
    @XmlSchemaType(name = "anySimpleType")
    protected String count;
    @XmlAttribute(name = "minObs")
    @XmlSchemaType(name = "anySimpleType")
    protected String minObs;
    @XmlAttribute(name = "maxObs")
    @XmlSchemaType(name = "anySimpleType")
    protected String maxObs;
    @XmlAttribute(name = "samplingType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String samplingType;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the mean property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMean() {
        if (mean == null) {
            return "0.0";
        } else {
            return mean;
        }
    }

    /**
     * Sets the value of the mean property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMean(String value) {
        this.mean = value;
    }

    /**
     * Gets the value of the variance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariance() {
        if (variance == null) {
            return "0.0";
        } else {
            return variance;
        }
    }

    /**
     * Sets the value of the variance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariance(String value) {
        this.variance = value;
    }

    /**
     * Gets the value of the standardDeviation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardDeviation() {
        if (standardDeviation == null) {
            return "0.0";
        } else {
            return standardDeviation;
        }
    }

    /**
     * Sets the value of the standardDeviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardDeviation(String value) {
        this.standardDeviation = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCount() {
        if (count == null) {
            return "0";
        } else {
            return count;
        }
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCount(String value) {
        this.count = value;
    }

    /**
     * Gets the value of the minObs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinObs() {
        if (minObs == null) {
            return "0.0";
        } else {
            return minObs;
        }
    }

    /**
     * Sets the value of the minObs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinObs(String value) {
        this.minObs = value;
    }

    /**
     * Gets the value of the maxObs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxObs() {
        if (maxObs == null) {
            return "0.0";
        } else {
            return maxObs;
        }
    }

    /**
     * Sets the value of the maxObs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxObs(String value) {
        this.maxObs = value;
    }

    /**
     * Gets the value of the samplingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamplingType() {
        if (samplingType == null) {
            return "TALLY";
        } else {
            return samplingType;
        }
    }

    /**
     * Sets the value of the samplingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamplingType(String value) {
        this.samplingType = value;
    }

}
