//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.13 at 11:41:18 AM PST 
//


package viskit.xsd.bindings.assembly;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="stopTime" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="0.0" /&gt;
 *       &lt;attribute name="verbose" default="true"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="numberReplications" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="1" /&gt;
 *       &lt;attribute name="printReplicationReports" default="true"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="printSummaryReport" default="true"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="saveReplicationData" default="true"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Schedule")
public class Schedule {

    @XmlAttribute(name = "stopTime")
    @XmlSchemaType(name = "anySimpleType")
    protected String stopTime;
    @XmlAttribute(name = "verbose")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String verbose;
    @XmlAttribute(name = "numberReplications")
    @XmlSchemaType(name = "anySimpleType")
    protected String numberReplications;
    @XmlAttribute(name = "printReplicationReports")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String printReplicationReports;
    @XmlAttribute(name = "printSummaryReport")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String printSummaryReport;
    @XmlAttribute(name = "saveReplicationData")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String saveReplicationData;

    /**
     * Gets the value of the stopTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopTime() {
        if (stopTime == null) {
            return "0.0";
        } else {
            return stopTime;
        }
    }

    /**
     * Sets the value of the stopTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopTime(String value) {
        this.stopTime = value;
    }

    /**
     * Gets the value of the verbose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerbose() {
        if (verbose == null) {
            return "true";
        } else {
            return verbose;
        }
    }

    /**
     * Sets the value of the verbose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerbose(String value) {
        this.verbose = value;
    }

    /**
     * Gets the value of the numberReplications property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberReplications() {
        if (numberReplications == null) {
            return "1";
        } else {
            return numberReplications;
        }
    }

    /**
     * Sets the value of the numberReplications property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberReplications(String value) {
        this.numberReplications = value;
    }

    /**
     * Gets the value of the printReplicationReports property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintReplicationReports() {
        if (printReplicationReports == null) {
            return "true";
        } else {
            return printReplicationReports;
        }
    }

    /**
     * Sets the value of the printReplicationReports property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintReplicationReports(String value) {
        this.printReplicationReports = value;
    }

    /**
     * Gets the value of the printSummaryReport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintSummaryReport() {
        if (printSummaryReport == null) {
            return "true";
        } else {
            return printSummaryReport;
        }
    }

    /**
     * Sets the value of the printSummaryReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintSummaryReport(String value) {
        this.printSummaryReport = value;
    }

    /**
     * Gets the value of the saveReplicationData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaveReplicationData() {
        if (saveReplicationData == null) {
            return "true";
        } else {
            return saveReplicationData;
        }
    }

    /**
     * Sets the value of the saveReplicationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaveReplicationData(String value) {
        this.saveReplicationData = value;
    }

}
