//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.13 at 11:41:18 AM PST 
//


package viskit.xsd.bindings.assembly;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}head" minOccurs="0"/&gt;
 *         &lt;group ref="{}DesignParameters" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}SimEntity" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}EventGraph" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}PropertyChangeListener" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}SimEventListenerConnection" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}PropertyChangeListenerConnection" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Adapter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Output" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Verbose" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Schedule" minOccurs="0"/&gt;
 *         &lt;element ref="{}Experiment" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *       &lt;attribute name="created" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="package" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *       &lt;attribute name="author" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="extend" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="viskit.assembly.ViskitAssembly" /&gt;
 *       &lt;attribute name="implement" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "designParameters",
    "simEntity",
    "eventGraph",
    "propertyChangeListener",
    "simEventListenerConnection",
    "propertyChangeListenerConnection",
    "adapter",
    "output",
    "verbose",
    "schedule",
    "experiment"
})
@XmlRootElement(name = "SimkitAssembly")
public class SimkitAssembly {

    protected Head head;
    @XmlElement(name = "TerminalParameter")
    protected List<TerminalParameter> designParameters;
    @XmlElement(name = "SimEntity")
    protected List<SimEntity> simEntity;
    @XmlElement(name = "EventGraph")
    protected List<EventGraph> eventGraph;
    @XmlElement(name = "PropertyChangeListener")
    protected List<PropertyChangeListener> propertyChangeListener;
    @XmlElement(name = "SimEventListenerConnection")
    protected List<SimEventListenerConnection> simEventListenerConnection;
    @XmlElement(name = "PropertyChangeListenerConnection")
    protected List<PropertyChangeListenerConnection> propertyChangeListenerConnection;
    @XmlElement(name = "Adapter")
    protected List<Adapter> adapter;
    @XmlElement(name = "Output")
    protected List<Output> output;
    @XmlElement(name = "Verbose")
    protected List<Verbose> verbose;
    @XmlElement(name = "Schedule")
    protected Schedule schedule;
    @XmlElement(name = "Experiment")
    protected Experiment experiment;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String name;
    @XmlAttribute(name = "created")
    @XmlSchemaType(name = "anySimpleType")
    protected String created;
    @XmlAttribute(name = "version")
    @XmlSchemaType(name = "anySimpleType")
    protected String version;
    @XmlAttribute(name = "package", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String _package;
    @XmlAttribute(name = "author")
    @XmlSchemaType(name = "anySimpleType")
    protected String author;
    @XmlAttribute(name = "extend")
    @XmlSchemaType(name = "anySimpleType")
    protected String extend;
    @XmlAttribute(name = "implement")
    @XmlSchemaType(name = "anySimpleType")
    protected String implement;
    @XmlAttribute(name = "description")
    @XmlSchemaType(name = "anySimpleType")
    protected String description;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link Head }
     *     
     */
    public Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link Head }
     *     
     */
    public void setHead(Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the designParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the designParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDesignParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TerminalParameter }
     * 
     * 
     */
    public List<TerminalParameter> getDesignParameters() {
        if (designParameters == null) {
            designParameters = new ArrayList<TerminalParameter>();
        }
        return this.designParameters;
    }

    /**
     * Gets the value of the simEntity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simEntity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimEntity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimEntity }
     * 
     * 
     */
    public List<SimEntity> getSimEntity() {
        if (simEntity == null) {
            simEntity = new ArrayList<SimEntity>();
        }
        return this.simEntity;
    }

    /**
     * Gets the value of the eventGraph property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventGraph property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventGraph().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventGraph }
     * 
     * 
     */
    public List<EventGraph> getEventGraph() {
        if (eventGraph == null) {
            eventGraph = new ArrayList<EventGraph>();
        }
        return this.eventGraph;
    }

    /**
     * Gets the value of the propertyChangeListener property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyChangeListener property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyChangeListener().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyChangeListener }
     * 
     * 
     */
    public List<PropertyChangeListener> getPropertyChangeListener() {
        if (propertyChangeListener == null) {
            propertyChangeListener = new ArrayList<PropertyChangeListener>();
        }
        return this.propertyChangeListener;
    }

    /**
     * Gets the value of the simEventListenerConnection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simEventListenerConnection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimEventListenerConnection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimEventListenerConnection }
     * 
     * 
     */
    public List<SimEventListenerConnection> getSimEventListenerConnection() {
        if (simEventListenerConnection == null) {
            simEventListenerConnection = new ArrayList<SimEventListenerConnection>();
        }
        return this.simEventListenerConnection;
    }

    /**
     * Gets the value of the propertyChangeListenerConnection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyChangeListenerConnection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyChangeListenerConnection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyChangeListenerConnection }
     * 
     * 
     */
    public List<PropertyChangeListenerConnection> getPropertyChangeListenerConnection() {
        if (propertyChangeListenerConnection == null) {
            propertyChangeListenerConnection = new ArrayList<PropertyChangeListenerConnection>();
        }
        return this.propertyChangeListenerConnection;
    }

    /**
     * Gets the value of the adapter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adapter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdapter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Adapter }
     * 
     * 
     */
    public List<Adapter> getAdapter() {
        if (adapter == null) {
            adapter = new ArrayList<Adapter>();
        }
        return this.adapter;
    }

    /**
     * Gets the value of the output property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the output property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Output }
     * 
     * 
     */
    public List<Output> getOutput() {
        if (output == null) {
            output = new ArrayList<Output>();
        }
        return this.output;
    }

    /**
     * Gets the value of the verbose property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verbose property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerbose().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Verbose }
     * 
     * 
     */
    public List<Verbose> getVerbose() {
        if (verbose == null) {
            verbose = new ArrayList<Verbose>();
        }
        return this.verbose;
    }

    /**
     * Gets the value of the schedule property.
     * 
     * @return
     *     possible object is
     *     {@link Schedule }
     *     
     */
    public Schedule getSchedule() {
        return schedule;
    }

    /**
     * Sets the value of the schedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schedule }
     *     
     */
    public void setSchedule(Schedule value) {
        this.schedule = value;
    }

    /**
     * Gets the value of the experiment property.
     * 
     * @return
     *     possible object is
     *     {@link Experiment }
     *     
     */
    public Experiment getExperiment() {
        return experiment;
    }

    /**
     * Sets the value of the experiment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Experiment }
     *     
     */
    public void setExperiment(Experiment value) {
        this.experiment = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreated(String value) {
        this.created = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the package property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackage() {
        return _package;
    }

    /**
     * Sets the value of the package property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackage(String value) {
        this._package = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the extend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtend() {
        if (extend == null) {
            return "viskit.assembly.ViskitAssembly";
        } else {
            return extend;
        }
    }

    /**
     * Sets the value of the extend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtend(String value) {
        this.extend = value;
    }

    /**
     * Gets the value of the implement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplement() {
        return implement;
    }

    /**
     * Sets the value of the implement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplement(String value) {
        this.implement = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
