/*
 Copyright (c) 1995-2016 held by the author(s).  All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
    * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and http://www.movesinstitute.org)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */
package viskit.view;

import edu.nps.util.LogUtils;
import java.awt.Dialog;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import viskit.ViskitGlobals;
import viskit.ViskitStatics;
import viskit.ViskitProject;
import viskit.control.AssemblyController;
import viskit.mvc.mvcController;
import viskit.view.dialog.ViskitProjectGenerationDialog3;

/**
 * Utility to help guide the user on Viskit start up options, or when a new
 * project need to be created during runtime
 *
 * @author Mike Bailey
 * @since Aug 2008
 * @version $Id$
 */
public class ViskitProjectButtonPanel extends javax.swing.JPanel {
	
    static final Logger LOG = LogUtils.getLogger(ViskitProjectButtonPanel.class);

    private static JDialog dialog;

    public static void showDialog() {
        ViskitProjectButtonPanel panel = new ViskitProjectButtonPanel();
        dialog = new JDialog((Dialog) null, true);  // modal
        dialog.setContentPane(panel);
        dialog.pack();

        // We don't want a JVM exit when the user closes this dialog and merely
        // disposing doesn't kill the JVM.  Will need to force user the use the
        // Exit button, or chose another project open or creation option
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

        // Dialog will appear in center screen
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }

    /** Creates new form ViskitProjectButtonPanel */
    public ViskitProjectButtonPanel() {
        initComponents();
		
		openButton.setVisible(false); // TODO fix
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        defaultButt = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        existingButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        defaultButt.setText("Open default project");
        defaultButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultButtActionPerformed(evt);
            }
        });

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Viskit Startup", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        setName("viskitProjectButtonPanel"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(openButton, gridBagConstraints);

        existingButton.setText("Open existing project");
        existingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(existingButton, gridBagConstraints);

        createButton.setText("Create new project");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(createButton, gridBagConstraints);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(exitButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    static boolean firstTime = true;

    /** I'm not happy about one minor aspect and that is if the user selects
     * this option, then cancels, Viskit will automatically create and open a
     * ${user.home}/MyViskitProjects/DefaultProject space
     *
     * @param evt the open an existing project event action
     */
private void existingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingButtonActionPerformed
    File projectDirectory;
    if (!firstTime)
	{
        mvcController assemblyController = ViskitGlobals.instance().getAssemblyController();
        if (assemblyController != null)
		{
            AssemblyView assemblyView = (AssemblyView) assemblyController.getView();

            if (assemblyView != null) {
                assemblyView.openProject();
            }
        }
    }
	else // firstTime during this execution
	{
        projectDirectory = ViskitProject.openProjectDirectory(null, ViskitProject.MY_VISKIT_PROJECTS_DIR);
		if ((projectDirectory.exists() && projectDirectory.isDirectory()))  // extra safety check
		{
  			ViskitStatics.setViskitProjectDirectory(projectDirectory);
// TODO
//            AssemblyController assemblyController = (AssemblyController) ViskitGlobals.instance().getAssemblyController();
//            assemblyController.openProject(projectDirectory);
			
			firstTime = !firstTime;
		}
		else
		{
			LOG.error("ViskitProjectButtonPanel illegal directory selected: " + projectDirectory.getAbsolutePath());
		}
        // TODO NOTE: We have no way of setting the first opened project here as the
        // controller hasn't been created yet to store that info when Viskit
        // first starts up
    }
    defaultButtActionPerformed(null);

}//GEN-LAST:event_existingButtonActionPerformed

private void defaultButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultButtActionPerformed
    // TODO setup differently, but for now...
    dialog.dispose();
    dialog = null;
}//GEN-LAST:event_defaultButtActionPerformed

private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
    File projectDirectory;

    // What we wish to do here is force the user to create a new project space
    // before letting them move on, or, open and existing project, or the only
    // other option is to exit
    do {
        ViskitProjectGenerationDialog3.showDialog();
        if (ViskitProjectGenerationDialog3.cancelled)
		{
            return;
        }
        String projectPath = ViskitProjectGenerationDialog3.projectPath;
        projectDirectory = new File(projectPath);
		
        if (projectDirectory.exists() && (projectDirectory.isFile() || projectDirectory.list().length > 0))
		{
            JOptionPane.showMessageDialog(this, "Chosen project name exists.");
        } 
		else
		{
            break; // out of do
        }
    } while (true);

    ViskitStatics.setViskitProjectDirectory(projectDirectory);

    // NOTE: We have no way of setting the first opened project here as the
    // controller hasn't been created yet to store that info when Viskit first
    // starts up

    // Since this dialog is modal, need to dispose() before we can move along in the startup
    defaultButtActionPerformed(null);

    // The work directory will have already been created by default as ViskitGlobals.init
    // was already called which creates the directory ${user.home}/.viskit
    // during constructor init
}//GEN-LAST:event_createButtonActionPerformed

private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
    defaultButtActionPerformed(null);

    // I don't like the idea of a SysExit call right here, but the way each
    // frame component needs to develop while starting Viskit; each has to
    // finish before the ViskitGlobals.instance().systemExit(0) call will work
    // properly, so, reluctantly...
    System.exit(0);
}//GEN-LAST:event_exitButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
//        ViskitApplicationFrame viskitApplicationFrame = new ViskitApplicationFrame(""); // no file
		
		// TODO fix
		
//		SplashScreenFrame2 viskitApplication = new SplashScreenFrame2();
//		String[] varArg = { };
//		viskitApplication.main(varArg);
    }//GEN-LAST:event_openButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JButton defaultButt;
    private javax.swing.JButton existingButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton openButton;
    // End of variables declaration//GEN-END:variables
}
