//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.13 at 11:41:17 AM PST 
//


package viskit.xsd.bindings.eventgraph;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{}Assignment"/&gt;
 *           &lt;element ref="{}Operation"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{}LocalVariableAssignment" minOccurs="0"/&gt;
 *         &lt;element ref="{}LocalVariableInvocation" minOccurs="0"/&gt;
 *         &lt;element ref="{}Code" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="state" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assignment",
    "operation",
    "localVariableAssignment",
    "localVariableInvocation",
    "code"
})
@XmlRootElement(name = "StateTransition")
public class StateTransition {

    @XmlElement(name = "Assignment")
    protected Assignment assignment;
    @XmlElement(name = "Operation")
    protected Operation operation;
    @XmlElement(name = "LocalVariableAssignment")
    protected LocalVariableAssignment localVariableAssignment;
    @XmlElement(name = "LocalVariableInvocation")
    protected LocalVariableInvocation localVariableInvocation;
    @XmlElement(name = "Code")
    protected List<String> code;
    @XmlAttribute(name = "state", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object state;
    @XmlAttribute(name = "index")
    @XmlSchemaType(name = "anySimpleType")
    protected String index;
    @XmlAttribute(name = "description")
    @XmlSchemaType(name = "anySimpleType")
    protected String description;

    /**
     * Gets the value of the assignment property.
     * 
     * @return
     *     possible object is
     *     {@link Assignment }
     *     
     */
    public Assignment getAssignment() {
        return assignment;
    }

    /**
     * Sets the value of the assignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assignment }
     *     
     */
    public void setAssignment(Assignment value) {
        this.assignment = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link Operation }
     *     
     */
    public Operation getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operation }
     *     
     */
    public void setOperation(Operation value) {
        this.operation = value;
    }

    /**
     * Gets the value of the localVariableAssignment property.
     * 
     * @return
     *     possible object is
     *     {@link LocalVariableAssignment }
     *     
     */
    public LocalVariableAssignment getLocalVariableAssignment() {
        return localVariableAssignment;
    }

    /**
     * Sets the value of the localVariableAssignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalVariableAssignment }
     *     
     */
    public void setLocalVariableAssignment(LocalVariableAssignment value) {
        this.localVariableAssignment = value;
    }

    /**
     * Gets the value of the localVariableInvocation property.
     * 
     * @return
     *     possible object is
     *     {@link LocalVariableInvocation }
     *     
     */
    public LocalVariableInvocation getLocalVariableInvocation() {
        return localVariableInvocation;
    }

    /**
     * Sets the value of the localVariableInvocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalVariableInvocation }
     *     
     */
    public void setLocalVariableInvocation(LocalVariableInvocation value) {
        this.localVariableInvocation = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the code property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCode() {
        if (code == null) {
            code = new ArrayList<String>();
        }
        return this.code;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setState(Object value) {
        this.state = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndex(String value) {
        this.index = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
