/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viskit;

import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 * New Viskit Application Frame
 * tutorial: https://netbeans.apache.org/tutorial/main/kb/docs/java/quickstart-gui/
 * @author brutzman
 */
public class ViskitApplication extends javax.swing.JFrame {

    private final static int INDEX_EVENTGRAPH_EDITOR_TAB = 0;
    private final static int INDEX_ASSEMBLY_EDITOR_TAB   = 1;
    private final static int INDEX_ASSEMBLY_RUN_TAB      = 2;
    private final static int INDEX_ANALYST_REPORT_TAB    = 3;
    
    /**
     * Creates new form NewViskitApplicationJFrame
     */
    public ViskitApplication()
    {
        initComponents();
        
        viskitTabbedPane.setSelectedIndex(INDEX_ASSEMBLY_EDITOR_TAB);
        
        setTitle(" Viskit for Discrete Event Simulation (DES) using Simkit");
        // TODO fix
        // https://stackoverflow.com/questions/15657569/how-to-set-icon-to-jframe
        ImageIcon imageIcon = new ImageIcon("images/ViskitLogo.png");
        setIconImage(imageIcon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viskitTabbedPane = new javax.swing.JTabbedPane();
        eventGraphEditorPanel = new javax.swing.JPanel();
        assemblyEditorPanel = new javax.swing.JPanel();
        designOfExperimentsPanel = new javax.swing.JPanel();
        runSimulationTabbedPane = new javax.swing.JTabbedPane();
        runLocalSimulationPanel = new javax.swing.JPanel();
        runClusterSimulationPanel = new javax.swing.JPanel();
        analystReportPanel = new javax.swing.JPanel();
        analystReportTabbedPane = new javax.swing.JTabbedPane();
        _1_HeaderPanel = new javax.swing.JPanel();
        _2_ExecutiveSummaryPanel = new javax.swing.JPanel();
        _3_SimulationLocationPanel = new javax.swing.JPanel();
        _4_AssemblyConfirgurationPanel = new javax.swing.JPanel();
        _5_EntityParametersPanel = new javax.swing.JPanel();
        _6_BehaviorDescriptionsPanel = new javax.swing.JPanel();
        _7_StatisticalResultsPanel = new javax.swing.JPanel();
        _8_ConclusionsRecommendationsPanel = new javax.swing.JPanel();
        viskitMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newViskitProjectMI = new javax.swing.JMenuItem();
        openViskitProjectMI = new javax.swing.JMenuItem();
        openRecentViskitProjectMI = new javax.swing.JMenuItem();
        closeViskitProjectMI = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        newEventGraphMI = new javax.swing.JMenuItem();
        openEventGraphMI = new javax.swing.JMenuItem();
        openRecentEventGraphMI = new javax.swing.JMenuItem();
        closeEventGraphMI = new javax.swing.JMenuItem();
        closeAllEventGraphsMI = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        newAssemblyMI = new javax.swing.JMenuItem();
        openAssemblyMI = new javax.swing.JMenuItem();
        openRecentAssemblyMI = new javax.swing.JMenuItem();
        closeAssemblyMI = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        zipMailViskitProjectMI = new javax.swing.JMenuItem();
        exitMI = new javax.swing.JMenuItem();
        eventGraphMenu = new javax.swing.JMenu();
        cutEventEditMenuItem = new javax.swing.JMenuItem();
        copyEventEditMenuItem = new javax.swing.JMenuItem();
        pasteEventEditMenuItem = new javax.swing.JMenuItem();
        deleteEventEditMenuItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        addEventNodeMenuItem = new javax.swing.JMenuItem();
        addSimulationParameterMenuItem = new javax.swing.JMenuItem();
        addStateVariableMenuItem = new javax.swing.JMenuItem();
        addSchedulingEdgeMenuItem = new javax.swing.JMenuItem();
        addCancellingEdgeMenuItem = new javax.swing.JMenuItem();
        addSelfReferencingSchedulingEdgeMenuItem = new javax.swing.JMenuItem();
        addSelfReferencingCancellingEdgeMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        undoEventEditMenuItem = new javax.swing.JMenuItem();
        redoEventEditMenuItem = new javax.swing.JMenuItem();
        assemblyMenu = new javax.swing.JMenu();
        cutAssemblyEditMenuItem = new javax.swing.JMenuItem();
        copyAssemblyEditMenuItem = new javax.swing.JMenuItem();
        pasteAssemblyEditMenuItem = new javax.swing.JMenuItem();
        deleteAssemblyEditMenuItem = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        addEventGraphMenuItem = new javax.swing.JMenuItem();
        addPropertyChangeListenerMenuItem = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        undoAssemblyEditMenuItem = new javax.swing.JMenuItem();
        redoAssemblyEditMenuItem = new javax.swing.JMenuItem();
        designOfExperimentsMenu = new javax.swing.JMenu();
        runAssemblyMenu = new javax.swing.JMenu();
        saveSimulationConsoleMI = new javax.swing.JMenuItem();
        viewConsoleTextEditorMI = new javax.swing.JMenuItem();
        analystReportMenu = new javax.swing.JMenu();
        displayAnalystReportHtmlMI = new javax.swing.JMenuItem();
        openAnotherAnalystReportMI = new javax.swing.JMenuItem();
        saveAnalystReportXml = new javax.swing.JMenuItem();
        viewAnalystReportXmlMI = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        viewSavedXmlMI = new javax.swing.JMenuItem();
        generateJavaSourceMI = new javax.swing.JMenuItem();
        saveScreenImageMI = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        tutorialMI = new javax.swing.JMenuItem();
        settingsMI = new javax.swing.JMenuItem();
        aboutMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Viskit"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout eventGraphEditorPanelLayout = new javax.swing.GroupLayout(eventGraphEditorPanel);
        eventGraphEditorPanel.setLayout(eventGraphEditorPanelLayout);
        eventGraphEditorPanelLayout.setHorizontalGroup(
            eventGraphEditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        eventGraphEditorPanelLayout.setVerticalGroup(
            eventGraphEditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Event Graph Editor", eventGraphEditorPanel);

        javax.swing.GroupLayout assemblyEditorPanelLayout = new javax.swing.GroupLayout(assemblyEditorPanel);
        assemblyEditorPanel.setLayout(assemblyEditorPanelLayout);
        assemblyEditorPanelLayout.setHorizontalGroup(
            assemblyEditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        assemblyEditorPanelLayout.setVerticalGroup(
            assemblyEditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Assembly Editor", assemblyEditorPanel);

        javax.swing.GroupLayout designOfExperimentsPanelLayout = new javax.swing.GroupLayout(designOfExperimentsPanel);
        designOfExperimentsPanel.setLayout(designOfExperimentsPanelLayout);
        designOfExperimentsPanelLayout.setHorizontalGroup(
            designOfExperimentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        designOfExperimentsPanelLayout.setVerticalGroup(
            designOfExperimentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Design of Experiments (DOE)", designOfExperimentsPanel);

        javax.swing.GroupLayout runLocalSimulationPanelLayout = new javax.swing.GroupLayout(runLocalSimulationPanel);
        runLocalSimulationPanel.setLayout(runLocalSimulationPanelLayout);
        runLocalSimulationPanelLayout.setHorizontalGroup(
            runLocalSimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        runLocalSimulationPanelLayout.setVerticalGroup(
            runLocalSimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        runSimulationTabbedPane.addTab("Run Local Simulation", runLocalSimulationPanel);

        runClusterSimulationPanel.setEnabled(false);

        javax.swing.GroupLayout runClusterSimulationPanelLayout = new javax.swing.GroupLayout(runClusterSimulationPanel);
        runClusterSimulationPanel.setLayout(runClusterSimulationPanelLayout);
        runClusterSimulationPanelLayout.setHorizontalGroup(
            runClusterSimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        runClusterSimulationPanelLayout.setVerticalGroup(
            runClusterSimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        runSimulationTabbedPane.addTab("Run Cluster Simulation", runClusterSimulationPanel);

        viskitTabbedPane.addTab("Run Simulation", runSimulationTabbedPane);

        javax.swing.GroupLayout _1_HeaderPanelLayout = new javax.swing.GroupLayout(_1_HeaderPanel);
        _1_HeaderPanel.setLayout(_1_HeaderPanelLayout);
        _1_HeaderPanelLayout.setHorizontalGroup(
            _1_HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _1_HeaderPanelLayout.setVerticalGroup(
            _1_HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("1 Header", _1_HeaderPanel);

        javax.swing.GroupLayout _2_ExecutiveSummaryPanelLayout = new javax.swing.GroupLayout(_2_ExecutiveSummaryPanel);
        _2_ExecutiveSummaryPanel.setLayout(_2_ExecutiveSummaryPanelLayout);
        _2_ExecutiveSummaryPanelLayout.setHorizontalGroup(
            _2_ExecutiveSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _2_ExecutiveSummaryPanelLayout.setVerticalGroup(
            _2_ExecutiveSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("2 ExecutiveSummary", _2_ExecutiveSummaryPanel);

        javax.swing.GroupLayout _3_SimulationLocationPanelLayout = new javax.swing.GroupLayout(_3_SimulationLocationPanel);
        _3_SimulationLocationPanel.setLayout(_3_SimulationLocationPanelLayout);
        _3_SimulationLocationPanelLayout.setHorizontalGroup(
            _3_SimulationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _3_SimulationLocationPanelLayout.setVerticalGroup(
            _3_SimulationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("3 Simulation Location", _3_SimulationLocationPanel);

        javax.swing.GroupLayout _4_AssemblyConfirgurationPanelLayout = new javax.swing.GroupLayout(_4_AssemblyConfirgurationPanel);
        _4_AssemblyConfirgurationPanel.setLayout(_4_AssemblyConfirgurationPanelLayout);
        _4_AssemblyConfirgurationPanelLayout.setHorizontalGroup(
            _4_AssemblyConfirgurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _4_AssemblyConfirgurationPanelLayout.setVerticalGroup(
            _4_AssemblyConfirgurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("4 Assembly Configuration", _4_AssemblyConfirgurationPanel);

        javax.swing.GroupLayout _5_EntityParametersPanelLayout = new javax.swing.GroupLayout(_5_EntityParametersPanel);
        _5_EntityParametersPanel.setLayout(_5_EntityParametersPanelLayout);
        _5_EntityParametersPanelLayout.setHorizontalGroup(
            _5_EntityParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _5_EntityParametersPanelLayout.setVerticalGroup(
            _5_EntityParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("5 Entity Parameters", _5_EntityParametersPanel);

        javax.swing.GroupLayout _6_BehaviorDescriptionsPanelLayout = new javax.swing.GroupLayout(_6_BehaviorDescriptionsPanel);
        _6_BehaviorDescriptionsPanel.setLayout(_6_BehaviorDescriptionsPanelLayout);
        _6_BehaviorDescriptionsPanelLayout.setHorizontalGroup(
            _6_BehaviorDescriptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _6_BehaviorDescriptionsPanelLayout.setVerticalGroup(
            _6_BehaviorDescriptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("6 Behavior Descriptions", _6_BehaviorDescriptionsPanel);

        javax.swing.GroupLayout _7_StatisticalResultsPanelLayout = new javax.swing.GroupLayout(_7_StatisticalResultsPanel);
        _7_StatisticalResultsPanel.setLayout(_7_StatisticalResultsPanelLayout);
        _7_StatisticalResultsPanelLayout.setHorizontalGroup(
            _7_StatisticalResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _7_StatisticalResultsPanelLayout.setVerticalGroup(
            _7_StatisticalResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("7 Statistical Results", _7_StatisticalResultsPanel);

        javax.swing.GroupLayout _8_ConclusionsRecommendationsPanelLayout = new javax.swing.GroupLayout(_8_ConclusionsRecommendationsPanel);
        _8_ConclusionsRecommendationsPanel.setLayout(_8_ConclusionsRecommendationsPanelLayout);
        _8_ConclusionsRecommendationsPanelLayout.setHorizontalGroup(
            _8_ConclusionsRecommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _8_ConclusionsRecommendationsPanelLayout.setVerticalGroup(
            _8_ConclusionsRecommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("8 Conclusions, Recommendations", _8_ConclusionsRecommendationsPanel);

        javax.swing.GroupLayout analystReportPanelLayout = new javax.swing.GroupLayout(analystReportPanel);
        analystReportPanel.setLayout(analystReportPanelLayout);
        analystReportPanelLayout.setHorizontalGroup(
            analystReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analystReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(analystReportTabbedPane)
                .addContainerGap())
        );
        analystReportPanelLayout.setVerticalGroup(
            analystReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analystReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(analystReportTabbedPane)
                .addContainerGap())
        );

        viskitTabbedPane.addTab("Analyst Report", analystReportPanel);

        fileMenu.setText("File  ");

        newViskitProjectMI.setMnemonic(KeyEvent.VK_N);
        newViskitProjectMI.setText("New Viskit Project");
        fileMenu.add(newViskitProjectMI);

        openViskitProjectMI.setMnemonic(KeyEvent.VK_O);
        openViskitProjectMI.setText("Open Viskit Project");
        openViskitProjectMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openViskitProjectMIActionPerformed(evt);
            }
        });
        fileMenu.add(openViskitProjectMI);

        openRecentViskitProjectMI.setMnemonic(KeyEvent.VK_R);
        openRecentViskitProjectMI.setText("Open Recent Viskit Project");
        openRecentViskitProjectMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRecentViskitProjectMIActionPerformed(evt);
            }
        });
        fileMenu.add(openRecentViskitProjectMI);

        closeViskitProjectMI.setMnemonic(KeyEvent.VK_O);
        closeViskitProjectMI.setText("Close Viskit Project");
        closeViskitProjectMI.setToolTipText("Close current project and all related files");
        closeViskitProjectMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeViskitProjectMIActionPerformed(evt);
            }
        });
        fileMenu.add(closeViskitProjectMI);
        fileMenu.add(jSeparator1);

        newEventGraphMI.setMnemonic(KeyEvent.VK_N);
        newEventGraphMI.setText("New Event Graph");
        fileMenu.add(newEventGraphMI);

        openEventGraphMI.setMnemonic(KeyEvent.VK_O);
        openEventGraphMI.setText("Open Event Graph");
        fileMenu.add(openEventGraphMI);

        openRecentEventGraphMI.setMnemonic(KeyEvent.VK_R);
        openRecentEventGraphMI.setText("Open Recent Event Graph");
        fileMenu.add(openRecentEventGraphMI);

        closeEventGraphMI.setMnemonic(KeyEvent.VK_C);
        closeEventGraphMI.setText("Close Event Graph");
        closeEventGraphMI.setToolTipText("Close selected event graph");
        fileMenu.add(closeEventGraphMI);

        closeAllEventGraphsMI.setMnemonic(KeyEvent.VK_A);
        closeAllEventGraphsMI.setText("Close All Event Graphs");
        closeAllEventGraphsMI.setToolTipText("Close all event graphs");
        fileMenu.add(closeAllEventGraphsMI);
        fileMenu.add(jSeparator2);

        newAssemblyMI.setMnemonic(KeyEvent.VK_N);
        newAssemblyMI.setText("New Assembly");
        fileMenu.add(newAssemblyMI);

        openAssemblyMI.setMnemonic(KeyEvent.VK_O);
        openAssemblyMI.setText("Open Assembly");
        fileMenu.add(openAssemblyMI);

        openRecentAssemblyMI.setMnemonic(KeyEvent.VK_R);
        openRecentAssemblyMI.setText("Open Recent Assembly");
        fileMenu.add(openRecentAssemblyMI);

        closeAssemblyMI.setMnemonic(KeyEvent.VK_C);
        closeAssemblyMI.setText("Close Assembly");
        closeAssemblyMI.setToolTipText("Close the assembly");
        fileMenu.add(closeAssemblyMI);
        fileMenu.add(jSeparator4);

        zipMailViskitProjectMI.setMnemonic(KeyEvent.VK_Z);
        zipMailViskitProjectMI.setText("Zip, Mail Viskit Project");
        zipMailViskitProjectMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipMailViskitProjectMIActionPerformed(evt);
            }
        });
        fileMenu.add(zipMailViskitProjectMI);

        exitMI.setMnemonic(KeyEvent.VK_X);
        exitMI.setText("Exit");
        fileMenu.add(exitMI);

        viskitMenuBar.add(fileMenu);

        eventGraphMenu.setText("Event Graph    ");
        eventGraphMenu.setActionCommand("Event Graph Editor");

        cutEventEditMenuItem.setMnemonic(KeyEvent.VK_X);
        cutEventEditMenuItem.setText("Cut");
        cutEventEditMenuItem.setToolTipText("Cut selected item");
        eventGraphMenu.add(cutEventEditMenuItem);

        copyEventEditMenuItem.setMnemonic(KeyEvent.VK_C);
        copyEventEditMenuItem.setText("Copy");
        copyEventEditMenuItem.setToolTipText("Copy selected item");
        eventGraphMenu.add(copyEventEditMenuItem);

        pasteEventEditMenuItem.setMnemonic(KeyEvent.VK_V);
        pasteEventEditMenuItem.setText("Paste");
        pasteEventEditMenuItem.setToolTipText("Paste selected item");
        eventGraphMenu.add(pasteEventEditMenuItem);

        deleteEventEditMenuItem.setMnemonic(KeyEvent.VK_V);
        deleteEventEditMenuItem.setText("Delete");
        deleteEventEditMenuItem.setToolTipText("Delete selected item");
        eventGraphMenu.add(deleteEventEditMenuItem);
        eventGraphMenu.add(jSeparator5);

        addEventNodeMenuItem.setMnemonic(KeyEvent.VK_A);
        addEventNodeMenuItem.setText("Add Event Node");
        addEventNodeMenuItem.setToolTipText("");
        eventGraphMenu.add(addEventNodeMenuItem);

        addSimulationParameterMenuItem.setText("Add Simulation Parameter");
        addSimulationParameterMenuItem.setToolTipText("");
        eventGraphMenu.add(addSimulationParameterMenuItem);

        addStateVariableMenuItem.setText("Add State Variable");
        addStateVariableMenuItem.setToolTipText("");
        eventGraphMenu.add(addStateVariableMenuItem);

        addSchedulingEdgeMenuItem.setText("Add Scheduling Edge");
        addSchedulingEdgeMenuItem.setToolTipText("");
        eventGraphMenu.add(addSchedulingEdgeMenuItem);

        addCancellingEdgeMenuItem.setText("Add Cancelling Edge");
        addCancellingEdgeMenuItem.setToolTipText("");
        eventGraphMenu.add(addCancellingEdgeMenuItem);

        addSelfReferencingSchedulingEdgeMenuItem.setText("Add Self-Referencing Scheduling Edge");
        addSelfReferencingSchedulingEdgeMenuItem.setToolTipText("");
        eventGraphMenu.add(addSelfReferencingSchedulingEdgeMenuItem);

        addSelfReferencingCancellingEdgeMenuItem.setText("Add Self-Referencing Cancelling Edge");
        addSelfReferencingCancellingEdgeMenuItem.setToolTipText("");
        eventGraphMenu.add(addSelfReferencingCancellingEdgeMenuItem);
        eventGraphMenu.add(jSeparator3);

        undoEventEditMenuItem.setMnemonic(KeyEvent.VK_U);
        undoEventEditMenuItem.setText("Undo");
        undoEventEditMenuItem.setToolTipText("Undo last action");
        eventGraphMenu.add(undoEventEditMenuItem);

        redoEventEditMenuItem.setMnemonic(KeyEvent.VK_R);
        redoEventEditMenuItem.setText("Redo");
        redoEventEditMenuItem.setToolTipText("Redo last undo");
        eventGraphMenu.add(redoEventEditMenuItem);

        viskitMenuBar.add(eventGraphMenu);

        assemblyMenu.setText("Assembly             ");

        cutAssemblyEditMenuItem.setMnemonic(KeyEvent.VK_X);
        cutAssemblyEditMenuItem.setText("Cut");
        cutAssemblyEditMenuItem.setToolTipText("Cut selected item");
        cutAssemblyEditMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutAssemblyEditMenuItemActionPerformed(evt);
            }
        });
        assemblyMenu.add(cutAssemblyEditMenuItem);

        copyAssemblyEditMenuItem.setMnemonic(KeyEvent.VK_C);
        copyAssemblyEditMenuItem.setText("Copy");
        copyAssemblyEditMenuItem.setToolTipText("Copy selected item");
        assemblyMenu.add(copyAssemblyEditMenuItem);

        pasteAssemblyEditMenuItem.setMnemonic(KeyEvent.VK_V);
        pasteAssemblyEditMenuItem.setText("Paste");
        pasteAssemblyEditMenuItem.setToolTipText("Paste selected item");
        assemblyMenu.add(pasteAssemblyEditMenuItem);

        deleteAssemblyEditMenuItem.setMnemonic(KeyEvent.VK_V);
        deleteAssemblyEditMenuItem.setText("Delete");
        deleteAssemblyEditMenuItem.setToolTipText("Delete selected item");
        assemblyMenu.add(deleteAssemblyEditMenuItem);
        assemblyMenu.add(jSeparator8);

        addEventGraphMenuItem.setMnemonic(KeyEvent.VK_A);
        addEventGraphMenuItem.setText("Add Event Graph");
        addEventGraphMenuItem.setToolTipText("");
        assemblyMenu.add(addEventGraphMenuItem);

        addPropertyChangeListenerMenuItem.setMnemonic(KeyEvent.VK_A);
        addPropertyChangeListenerMenuItem.setText("Add Property Change Listener");
        addPropertyChangeListenerMenuItem.setToolTipText("");
        assemblyMenu.add(addPropertyChangeListenerMenuItem);
        assemblyMenu.add(jSeparator6);

        undoAssemblyEditMenuItem.setMnemonic(KeyEvent.VK_U);
        undoAssemblyEditMenuItem.setText("Undo");
        undoAssemblyEditMenuItem.setToolTipText("Undo last action");
        assemblyMenu.add(undoAssemblyEditMenuItem);

        redoAssemblyEditMenuItem.setMnemonic(KeyEvent.VK_R);
        redoAssemblyEditMenuItem.setText("Redo");
        redoAssemblyEditMenuItem.setToolTipText("Redo last undo");
        assemblyMenu.add(redoAssemblyEditMenuItem);

        viskitMenuBar.add(assemblyMenu);

        designOfExperimentsMenu.setText("Design of Experiments (DOE)   ");
        viskitMenuBar.add(designOfExperimentsMenu);

        runAssemblyMenu.setText("Run Simulation  ");

        saveSimulationConsoleMI.setMnemonic(KeyEvent.VK_S);
        saveSimulationConsoleMI.setText("Save Simulation Console");
        runAssemblyMenu.add(saveSimulationConsoleMI);

        viewConsoleTextEditorMI.setMnemonic(KeyEvent.VK_V);
        viewConsoleTextEditorMI.setText("View Console in Text Editor");
        runAssemblyMenu.add(viewConsoleTextEditorMI);

        viskitMenuBar.add(runAssemblyMenu);

        analystReportMenu.setText("Analyst Report");

        displayAnalystReportHtmlMI.setMnemonic(KeyEvent.VK_D);
        displayAnalystReportHtmlMI.setText("Display Analyst Report HTML");
        displayAnalystReportHtmlMI.setToolTipText("Display Analyst Report in Web browser");
        analystReportMenu.add(displayAnalystReportHtmlMI);

        openAnotherAnalystReportMI.setMnemonic(KeyEvent.VK_O);
        openAnotherAnalystReportMI.setText("Open another Analyst Report");
        analystReportMenu.add(openAnotherAnalystReportMI);

        saveAnalystReportXml.setMnemonic(KeyEvent.VK_S);
        saveAnalystReportXml.setText("Save Analyst Report XML");
        analystReportMenu.add(saveAnalystReportXml);

        viewAnalystReportXmlMI.setMnemonic(KeyEvent.VK_V);
        viewAnalystReportXmlMI.setText("View Analyst Report XML");
        analystReportMenu.add(viewAnalystReportXmlMI);

        viskitMenuBar.add(analystReportMenu);

        viewMenu.setText("View");

        viewSavedXmlMI.setMnemonic(KeyEvent.VK_V);
        viewSavedXmlMI.setText("View Saved XML");
        viewMenu.add(viewSavedXmlMI);

        generateJavaSourceMI.setMnemonic(KeyEvent.VK_G);
        generateJavaSourceMI.setText("Generate Java Source");
        viewMenu.add(generateJavaSourceMI);

        saveScreenImageMI.setMnemonic(KeyEvent.VK_I);
        saveScreenImageMI.setText("Save Screen Image");
        viewMenu.add(saveScreenImageMI);

        viskitMenuBar.add(viewMenu);

        helpMenu.setText("Help");

        tutorialMI.setMnemonic(KeyEvent.VK_T);
        tutorialMI.setText("Tutorial");
        helpMenu.add(tutorialMI);

        settingsMI.setMnemonic(KeyEvent.VK_U);
        settingsMI.setText("User settings");
        settingsMI.setToolTipText("User settings for Viskit application");
        helpMenu.add(settingsMI);

        aboutMI.setMnemonic(KeyEvent.VK_A);
        aboutMI.setText("About Viskit");
        helpMenu.add(aboutMI);

        viskitMenuBar.add(helpMenu);

        setJMenuBar(viskitMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viskitTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viskitTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zipMailViskitProjectMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipMailViskitProjectMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipMailViskitProjectMIActionPerformed

    private void openViskitProjectMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openViskitProjectMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openViskitProjectMIActionPerformed

    private void openRecentViskitProjectMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openRecentViskitProjectMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openRecentViskitProjectMIActionPerformed

    private void closeViskitProjectMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeViskitProjectMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeViskitProjectMIActionPerformed

    private void cutAssemblyEditMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutAssemblyEditMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutAssemblyEditMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } 
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) 
        {
            java.util.logging.Logger.getLogger(ViskitApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViskitApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _1_HeaderPanel;
    private javax.swing.JPanel _2_ExecutiveSummaryPanel;
    private javax.swing.JPanel _3_SimulationLocationPanel;
    private javax.swing.JPanel _4_AssemblyConfirgurationPanel;
    private javax.swing.JPanel _5_EntityParametersPanel;
    private javax.swing.JPanel _6_BehaviorDescriptionsPanel;
    private javax.swing.JPanel _7_StatisticalResultsPanel;
    private javax.swing.JPanel _8_ConclusionsRecommendationsPanel;
    private javax.swing.JMenuItem aboutMI;
    private javax.swing.JMenuItem addCancellingEdgeMenuItem;
    private javax.swing.JMenuItem addEventGraphMenuItem;
    private javax.swing.JMenuItem addEventNodeMenuItem;
    private javax.swing.JMenuItem addPropertyChangeListenerMenuItem;
    private javax.swing.JMenuItem addSchedulingEdgeMenuItem;
    private javax.swing.JMenuItem addSelfReferencingCancellingEdgeMenuItem;
    private javax.swing.JMenuItem addSelfReferencingSchedulingEdgeMenuItem;
    private javax.swing.JMenuItem addSimulationParameterMenuItem;
    private javax.swing.JMenuItem addStateVariableMenuItem;
    private javax.swing.JMenu analystReportMenu;
    private javax.swing.JPanel analystReportPanel;
    private javax.swing.JTabbedPane analystReportTabbedPane;
    private javax.swing.JPanel assemblyEditorPanel;
    private javax.swing.JMenu assemblyMenu;
    private javax.swing.JMenuItem closeAllEventGraphsMI;
    private javax.swing.JMenuItem closeAssemblyMI;
    private javax.swing.JMenuItem closeEventGraphMI;
    private javax.swing.JMenuItem closeViskitProjectMI;
    private javax.swing.JMenuItem copyAssemblyEditMenuItem;
    private javax.swing.JMenuItem copyEventEditMenuItem;
    private javax.swing.JMenuItem cutAssemblyEditMenuItem;
    private javax.swing.JMenuItem cutEventEditMenuItem;
    private javax.swing.JMenuItem deleteAssemblyEditMenuItem;
    private javax.swing.JMenuItem deleteEventEditMenuItem;
    private javax.swing.JMenu designOfExperimentsMenu;
    private javax.swing.JPanel designOfExperimentsPanel;
    private javax.swing.JMenuItem displayAnalystReportHtmlMI;
    private javax.swing.JPanel eventGraphEditorPanel;
    private javax.swing.JMenu eventGraphMenu;
    private javax.swing.JMenuItem exitMI;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem generateJavaSourceMI;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JMenuItem newAssemblyMI;
    private javax.swing.JMenuItem newEventGraphMI;
    private javax.swing.JMenuItem newViskitProjectMI;
    private javax.swing.JMenuItem openAnotherAnalystReportMI;
    private javax.swing.JMenuItem openAssemblyMI;
    private javax.swing.JMenuItem openEventGraphMI;
    private javax.swing.JMenuItem openRecentAssemblyMI;
    private javax.swing.JMenuItem openRecentEventGraphMI;
    private javax.swing.JMenuItem openRecentViskitProjectMI;
    private javax.swing.JMenuItem openViskitProjectMI;
    private javax.swing.JMenuItem pasteAssemblyEditMenuItem;
    private javax.swing.JMenuItem pasteEventEditMenuItem;
    private javax.swing.JMenuItem redoAssemblyEditMenuItem;
    private javax.swing.JMenuItem redoEventEditMenuItem;
    private javax.swing.JMenu runAssemblyMenu;
    private javax.swing.JPanel runClusterSimulationPanel;
    private javax.swing.JPanel runLocalSimulationPanel;
    private javax.swing.JTabbedPane runSimulationTabbedPane;
    private javax.swing.JMenuItem saveAnalystReportXml;
    private javax.swing.JMenuItem saveScreenImageMI;
    private javax.swing.JMenuItem saveSimulationConsoleMI;
    private javax.swing.JMenuItem settingsMI;
    private javax.swing.JMenuItem tutorialMI;
    private javax.swing.JMenuItem undoAssemblyEditMenuItem;
    private javax.swing.JMenuItem undoEventEditMenuItem;
    private javax.swing.JMenuItem viewAnalystReportXmlMI;
    private javax.swing.JMenuItem viewConsoleTextEditorMI;
    private javax.swing.JMenu viewMenu;
    private javax.swing.JMenuItem viewSavedXmlMI;
    private javax.swing.JMenuBar viskitMenuBar;
    private javax.swing.JTabbedPane viskitTabbedPane;
    private javax.swing.JMenuItem zipMailViskitProjectMI;
    // End of variables declaration//GEN-END:variables
}
