/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viskit;

import javax.swing.ImageIcon;

/**
 * New Viskit Aoplication Frame
 * tutorial: https://netbeans.apache.org/tutorial/main/kb/docs/java/quickstart-gui/
 * @author brutzman
 */
public class ViskitApplication extends javax.swing.JFrame {

    /**
     * Creates new form NewViskitApplicationJFrame
     */
    public ViskitApplication() {
        initComponents();
        
        setTitle("Viskit");
        // TODO fix
        // https://stackoverflow.com/questions/15657569/how-to-set-icon-to-jframe
        ImageIcon imageIcon = new ImageIcon("images/ViskitLogo.png");
        setIconImage(imageIcon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viskitTabbedPane = new javax.swing.JTabbedPane();
        eventGraphEditorPanel = new javax.swing.JPanel();
        assemblyEditorPanel = new javax.swing.JPanel();
        assemblyRunPanel = new javax.swing.JPanel();
        designOfExperimentsPanel = new javax.swing.JPanel();
        clusterRunPanel = new javax.swing.JPanel();
        analystReportPanel = new javax.swing.JPanel();
        viskitMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        editMenu = new javax.swing.JMenu();
        eventGraphEditorMenu = new javax.swing.JMenu();
        assemblyEditorMenu = new javax.swing.JMenu();
        assemblyRunMenu = new javax.swing.JMenu();
        designOfExperimentsMenu = new javax.swing.JMenu();
        clusterRunMenu = new javax.swing.JMenu();
        analystReportMenu = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Viskit"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout eventGraphEditorPanelLayout = new javax.swing.GroupLayout(eventGraphEditorPanel);
        eventGraphEditorPanel.setLayout(eventGraphEditorPanelLayout);
        eventGraphEditorPanelLayout.setHorizontalGroup(
            eventGraphEditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        eventGraphEditorPanelLayout.setVerticalGroup(
            eventGraphEditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Event Graph Editor", eventGraphEditorPanel);

        javax.swing.GroupLayout assemblyEditorPanelLayout = new javax.swing.GroupLayout(assemblyEditorPanel);
        assemblyEditorPanel.setLayout(assemblyEditorPanelLayout);
        assemblyEditorPanelLayout.setHorizontalGroup(
            assemblyEditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        assemblyEditorPanelLayout.setVerticalGroup(
            assemblyEditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Assembly Editor", assemblyEditorPanel);

        javax.swing.GroupLayout assemblyRunPanelLayout = new javax.swing.GroupLayout(assemblyRunPanel);
        assemblyRunPanel.setLayout(assemblyRunPanelLayout);
        assemblyRunPanelLayout.setHorizontalGroup(
            assemblyRunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        assemblyRunPanelLayout.setVerticalGroup(
            assemblyRunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Assembly Run", assemblyRunPanel);

        javax.swing.GroupLayout designOfExperimentsPanelLayout = new javax.swing.GroupLayout(designOfExperimentsPanel);
        designOfExperimentsPanel.setLayout(designOfExperimentsPanelLayout);
        designOfExperimentsPanelLayout.setHorizontalGroup(
            designOfExperimentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        designOfExperimentsPanelLayout.setVerticalGroup(
            designOfExperimentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Design of Experiments", designOfExperimentsPanel);

        clusterRunPanel.setEnabled(false);

        javax.swing.GroupLayout clusterRunPanelLayout = new javax.swing.GroupLayout(clusterRunPanel);
        clusterRunPanel.setLayout(clusterRunPanelLayout);
        clusterRunPanelLayout.setHorizontalGroup(
            clusterRunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        clusterRunPanelLayout.setVerticalGroup(
            clusterRunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Cluster Run", clusterRunPanel);

        javax.swing.GroupLayout analystReportPanelLayout = new javax.swing.GroupLayout(analystReportPanel);
        analystReportPanel.setLayout(analystReportPanelLayout);
        analystReportPanelLayout.setHorizontalGroup(
            analystReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        analystReportPanelLayout.setVerticalGroup(
            analystReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Analyst Report", analystReportPanel);

        fileMenu.setText("File");
        viskitMenuBar.add(fileMenu);

        editMenu.setText("Edit");
        viskitMenuBar.add(editMenu);

        eventGraphEditorMenu.setText("Event Graph Editor");
        eventGraphEditorMenu.setActionCommand("Event Graph Editor");
        viskitMenuBar.add(eventGraphEditorMenu);

        assemblyEditorMenu.setText("Assembly Editor");
        viskitMenuBar.add(assemblyEditorMenu);

        assemblyRunMenu.setText("Assembly Run");
        viskitMenuBar.add(assemblyRunMenu);

        designOfExperimentsMenu.setText("Design of Experiments");
        viskitMenuBar.add(designOfExperimentsMenu);

        clusterRunMenu.setText("Cluster Run");
        clusterRunMenu.setEnabled(false);
        viskitMenuBar.add(clusterRunMenu);

        analystReportMenu.setText("Analyst Report");
        viskitMenuBar.add(analystReportMenu);

        helpMenu.setText("Help");
        viskitMenuBar.add(helpMenu);

        setJMenuBar(viskitMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viskitTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viskitTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViskitApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViskitApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViskitApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViskitApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViskitApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu analystReportMenu;
    private javax.swing.JPanel analystReportPanel;
    private javax.swing.JMenu assemblyEditorMenu;
    private javax.swing.JPanel assemblyEditorPanel;
    private javax.swing.JMenu assemblyRunMenu;
    private javax.swing.JPanel assemblyRunPanel;
    private javax.swing.JMenu clusterRunMenu;
    private javax.swing.JPanel clusterRunPanel;
    private javax.swing.JMenu designOfExperimentsMenu;
    private javax.swing.JPanel designOfExperimentsPanel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu eventGraphEditorMenu;
    private javax.swing.JPanel eventGraphEditorPanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar viskitMenuBar;
    private javax.swing.JTabbedPane viskitTabbedPane;
    // End of variables declaration//GEN-END:variables
}
