/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viskit;

import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 * New Viskit Application Frame
 * tutorial: https://netbeans.apache.org/tutorial/main/kb/docs/java/quickstart-gui/
 * @author brutzman
 */
public class ViskitApplication extends javax.swing.JFrame {

    /**
     * Creates new form NewViskitApplicationJFrame
     */
    public ViskitApplication() {
        initComponents();
        
        setTitle("Viskit");
        // TODO fix
        // https://stackoverflow.com/questions/15657569/how-to-set-icon-to-jframe
        ImageIcon imageIcon = new ImageIcon("images/ViskitLogo.png");
        setIconImage(imageIcon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viskitTabbedPane = new javax.swing.JTabbedPane();
        eventGraphEditorPanel = new javax.swing.JPanel();
        assemblyEditorPanel = new javax.swing.JPanel();
        runAssemblyPanel = new javax.swing.JPanel();
        designOfExperimentsPanel = new javax.swing.JPanel();
        clusterRunPanel = new javax.swing.JPanel();
        analystReportPanel = new javax.swing.JPanel();
        analystReportTabbedPane = new javax.swing.JTabbedPane();
        _1_HeaderPanel = new javax.swing.JPanel();
        _2_ExecutiveSummaryPanel = new javax.swing.JPanel();
        _3_SimulationLocationPanel = new javax.swing.JPanel();
        _4_AssemblyConfirgurationPanel = new javax.swing.JPanel();
        _5_EntityParametersPanel = new javax.swing.JPanel();
        _6_BehaviorDescriptionsPanel = new javax.swing.JPanel();
        _7_StatisticalResultsPanel = new javax.swing.JPanel();
        _8_ConclusionsRecommendationsPanel = new javax.swing.JPanel();
        viskitMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newViskitProjectMI = new javax.swing.JMenuItem();
        zipMailViskitProjectMI = new javax.swing.JMenuItem();
        viewSavedXmlMI = new javax.swing.JMenuItem();
        generateJavaSourceMI = new javax.swing.JMenuItem();
        saveScreenImageMI = new javax.swing.JMenuItem();
        settingsMI = new javax.swing.JMenuItem();
        exitMI = new javax.swing.JMenuItem();
        eventGraphMenu = new javax.swing.JMenu();
        assemblyMenu = new javax.swing.JMenu();
        runAssemblyMenu = new javax.swing.JMenu();
        designOfExperimentsMenu = new javax.swing.JMenu();
        clusterRunMenu = new javax.swing.JMenu();
        analystReportMenu = new javax.swing.JMenu();
        displayAnalystReportHtmlMI = new javax.swing.JMenuItem();
        openAnotherAnalystReportMI = new javax.swing.JMenuItem();
        saveAnalystReportXml = new javax.swing.JMenuItem();
        viewAnalystReportXmlMI = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        tutorialMI = new javax.swing.JMenuItem();
        aboutMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Viskit"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout eventGraphEditorPanelLayout = new javax.swing.GroupLayout(eventGraphEditorPanel);
        eventGraphEditorPanel.setLayout(eventGraphEditorPanelLayout);
        eventGraphEditorPanelLayout.setHorizontalGroup(
            eventGraphEditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        eventGraphEditorPanelLayout.setVerticalGroup(
            eventGraphEditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Event Graph Editor", eventGraphEditorPanel);

        javax.swing.GroupLayout assemblyEditorPanelLayout = new javax.swing.GroupLayout(assemblyEditorPanel);
        assemblyEditorPanel.setLayout(assemblyEditorPanelLayout);
        assemblyEditorPanelLayout.setHorizontalGroup(
            assemblyEditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        assemblyEditorPanelLayout.setVerticalGroup(
            assemblyEditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Assembly Editor", assemblyEditorPanel);

        javax.swing.GroupLayout runAssemblyPanelLayout = new javax.swing.GroupLayout(runAssemblyPanel);
        runAssemblyPanel.setLayout(runAssemblyPanelLayout);
        runAssemblyPanelLayout.setHorizontalGroup(
            runAssemblyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        runAssemblyPanelLayout.setVerticalGroup(
            runAssemblyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Run Assembly", runAssemblyPanel);

        javax.swing.GroupLayout designOfExperimentsPanelLayout = new javax.swing.GroupLayout(designOfExperimentsPanel);
        designOfExperimentsPanel.setLayout(designOfExperimentsPanelLayout);
        designOfExperimentsPanelLayout.setHorizontalGroup(
            designOfExperimentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        designOfExperimentsPanelLayout.setVerticalGroup(
            designOfExperimentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Design of Experiments (DOE)", designOfExperimentsPanel);

        clusterRunPanel.setEnabled(false);

        javax.swing.GroupLayout clusterRunPanelLayout = new javax.swing.GroupLayout(clusterRunPanel);
        clusterRunPanel.setLayout(clusterRunPanelLayout);
        clusterRunPanelLayout.setHorizontalGroup(
            clusterRunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        clusterRunPanelLayout.setVerticalGroup(
            clusterRunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        viskitTabbedPane.addTab("Cluster Run", clusterRunPanel);

        javax.swing.GroupLayout _1_HeaderPanelLayout = new javax.swing.GroupLayout(_1_HeaderPanel);
        _1_HeaderPanel.setLayout(_1_HeaderPanelLayout);
        _1_HeaderPanelLayout.setHorizontalGroup(
            _1_HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _1_HeaderPanelLayout.setVerticalGroup(
            _1_HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("1 Header", _1_HeaderPanel);

        javax.swing.GroupLayout _2_ExecutiveSummaryPanelLayout = new javax.swing.GroupLayout(_2_ExecutiveSummaryPanel);
        _2_ExecutiveSummaryPanel.setLayout(_2_ExecutiveSummaryPanelLayout);
        _2_ExecutiveSummaryPanelLayout.setHorizontalGroup(
            _2_ExecutiveSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _2_ExecutiveSummaryPanelLayout.setVerticalGroup(
            _2_ExecutiveSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("2 ExecutiveSummary", _2_ExecutiveSummaryPanel);

        javax.swing.GroupLayout _3_SimulationLocationPanelLayout = new javax.swing.GroupLayout(_3_SimulationLocationPanel);
        _3_SimulationLocationPanel.setLayout(_3_SimulationLocationPanelLayout);
        _3_SimulationLocationPanelLayout.setHorizontalGroup(
            _3_SimulationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _3_SimulationLocationPanelLayout.setVerticalGroup(
            _3_SimulationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("3 Simulation Location", _3_SimulationLocationPanel);

        javax.swing.GroupLayout _4_AssemblyConfirgurationPanelLayout = new javax.swing.GroupLayout(_4_AssemblyConfirgurationPanel);
        _4_AssemblyConfirgurationPanel.setLayout(_4_AssemblyConfirgurationPanelLayout);
        _4_AssemblyConfirgurationPanelLayout.setHorizontalGroup(
            _4_AssemblyConfirgurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _4_AssemblyConfirgurationPanelLayout.setVerticalGroup(
            _4_AssemblyConfirgurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("4 Assembly Configuration", _4_AssemblyConfirgurationPanel);

        javax.swing.GroupLayout _5_EntityParametersPanelLayout = new javax.swing.GroupLayout(_5_EntityParametersPanel);
        _5_EntityParametersPanel.setLayout(_5_EntityParametersPanelLayout);
        _5_EntityParametersPanelLayout.setHorizontalGroup(
            _5_EntityParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _5_EntityParametersPanelLayout.setVerticalGroup(
            _5_EntityParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("5 Entity Parameters", _5_EntityParametersPanel);

        javax.swing.GroupLayout _6_BehaviorDescriptionsPanelLayout = new javax.swing.GroupLayout(_6_BehaviorDescriptionsPanel);
        _6_BehaviorDescriptionsPanel.setLayout(_6_BehaviorDescriptionsPanelLayout);
        _6_BehaviorDescriptionsPanelLayout.setHorizontalGroup(
            _6_BehaviorDescriptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _6_BehaviorDescriptionsPanelLayout.setVerticalGroup(
            _6_BehaviorDescriptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("tab1", _6_BehaviorDescriptionsPanel);

        javax.swing.GroupLayout _7_StatisticalResultsPanelLayout = new javax.swing.GroupLayout(_7_StatisticalResultsPanel);
        _7_StatisticalResultsPanel.setLayout(_7_StatisticalResultsPanelLayout);
        _7_StatisticalResultsPanelLayout.setHorizontalGroup(
            _7_StatisticalResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _7_StatisticalResultsPanelLayout.setVerticalGroup(
            _7_StatisticalResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("tab1", _7_StatisticalResultsPanel);

        javax.swing.GroupLayout _8_ConclusionsRecommendationsPanelLayout = new javax.swing.GroupLayout(_8_ConclusionsRecommendationsPanel);
        _8_ConclusionsRecommendationsPanel.setLayout(_8_ConclusionsRecommendationsPanelLayout);
        _8_ConclusionsRecommendationsPanelLayout.setHorizontalGroup(
            _8_ConclusionsRecommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        _8_ConclusionsRecommendationsPanelLayout.setVerticalGroup(
            _8_ConclusionsRecommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        analystReportTabbedPane.addTab("tab1", _8_ConclusionsRecommendationsPanel);

        javax.swing.GroupLayout analystReportPanelLayout = new javax.swing.GroupLayout(analystReportPanel);
        analystReportPanel.setLayout(analystReportPanelLayout);
        analystReportPanelLayout.setHorizontalGroup(
            analystReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analystReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(analystReportTabbedPane)
                .addContainerGap())
        );
        analystReportPanelLayout.setVerticalGroup(
            analystReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analystReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(analystReportTabbedPane)
                .addContainerGap())
        );

        viskitTabbedPane.addTab("Analyst Report", analystReportPanel);

        fileMenu.setText("File");

        newViskitProjectMI.setMnemonic(KeyEvent.VK_N);
        newViskitProjectMI.setText("New Viskit Project");
        fileMenu.add(newViskitProjectMI);

        zipMailViskitProjectMI.setMnemonic(KeyEvent.VK_Z);
        zipMailViskitProjectMI.setText("New Viskit Project");
        zipMailViskitProjectMI.setActionCommand("Zip, Mail Viskit Project");
        zipMailViskitProjectMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipMailViskitProjectMIActionPerformed(evt);
            }
        });
        fileMenu.add(zipMailViskitProjectMI);

        viewSavedXmlMI.setMnemonic(KeyEvent.VK_V);
        viewSavedXmlMI.setText("New Viskit Project");
        viewSavedXmlMI.setActionCommand("View Saved XML");
        fileMenu.add(viewSavedXmlMI);

        generateJavaSourceMI.setMnemonic(KeyEvent.VK_G);
        generateJavaSourceMI.setText("Generate Java Source");
        fileMenu.add(generateJavaSourceMI);

        saveScreenImageMI.setMnemonic(KeyEvent.VK_I);
        saveScreenImageMI.setText("Save Screen Image");
        fileMenu.add(saveScreenImageMI);

        settingsMI.setMnemonic(KeyEvent.VK_S);
        settingsMI.setText("Settings");
        settingsMI.setToolTipText("");
        fileMenu.add(settingsMI);

        exitMI.setMnemonic(KeyEvent.VK_X);
        exitMI.setText("Exit");
        fileMenu.add(exitMI);

        viskitMenuBar.add(fileMenu);

        eventGraphMenu.setText("Event Graph");
        eventGraphMenu.setActionCommand("Event Graph Editor");
        viskitMenuBar.add(eventGraphMenu);

        assemblyMenu.setText("Assembly");
        viskitMenuBar.add(assemblyMenu);

        runAssemblyMenu.setText("Run Assembly");
        viskitMenuBar.add(runAssemblyMenu);

        designOfExperimentsMenu.setText("Design of Experiments");
        viskitMenuBar.add(designOfExperimentsMenu);

        clusterRunMenu.setText("Cluster Run");
        viskitMenuBar.add(clusterRunMenu);

        analystReportMenu.setText("Analyst Report");

        displayAnalystReportHtmlMI.setMnemonic(KeyEvent.VK_D);
        displayAnalystReportHtmlMI.setText("Display Analyst Report XML");
        analystReportMenu.add(displayAnalystReportHtmlMI);

        openAnotherAnalystReportMI.setMnemonic(KeyEvent.VK_O);
        openAnotherAnalystReportMI.setText("Open another Analyst Report");
        analystReportMenu.add(openAnotherAnalystReportMI);

        saveAnalystReportXml.setMnemonic(KeyEvent.VK_S);
        saveAnalystReportXml.setText("Save Analyst Report Xml");
        analystReportMenu.add(saveAnalystReportXml);

        viewAnalystReportXmlMI.setMnemonic(KeyEvent.VK_V);
        viewAnalystReportXmlMI.setText("View Analyst Report XML");
        analystReportMenu.add(viewAnalystReportXmlMI);

        viskitMenuBar.add(analystReportMenu);

        helpMenu.setText("Help");

        tutorialMI.setMnemonic(KeyEvent.VK_T);
        tutorialMI.setText("Tutorial");
        helpMenu.add(tutorialMI);

        aboutMI.setMnemonic(KeyEvent.VK_A);
        aboutMI.setText("About");
        helpMenu.add(aboutMI);

        viskitMenuBar.add(helpMenu);

        setJMenuBar(viskitMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viskitTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viskitTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zipMailViskitProjectMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipMailViskitProjectMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipMailViskitProjectMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViskitApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViskitApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViskitApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViskitApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViskitApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _1_HeaderPanel;
    private javax.swing.JPanel _2_ExecutiveSummaryPanel;
    private javax.swing.JPanel _3_SimulationLocationPanel;
    private javax.swing.JPanel _4_AssemblyConfirgurationPanel;
    private javax.swing.JPanel _5_EntityParametersPanel;
    private javax.swing.JPanel _6_BehaviorDescriptionsPanel;
    private javax.swing.JPanel _7_StatisticalResultsPanel;
    private javax.swing.JPanel _8_ConclusionsRecommendationsPanel;
    private javax.swing.JMenuItem aboutMI;
    private javax.swing.JMenu analystReportMenu;
    private javax.swing.JPanel analystReportPanel;
    private javax.swing.JTabbedPane analystReportTabbedPane;
    private javax.swing.JPanel assemblyEditorPanel;
    private javax.swing.JMenu assemblyMenu;
    private javax.swing.JMenu clusterRunMenu;
    private javax.swing.JPanel clusterRunPanel;
    private javax.swing.JMenu designOfExperimentsMenu;
    private javax.swing.JPanel designOfExperimentsPanel;
    private javax.swing.JMenuItem displayAnalystReportHtmlMI;
    private javax.swing.JPanel eventGraphEditorPanel;
    private javax.swing.JMenu eventGraphMenu;
    private javax.swing.JMenuItem exitMI;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem generateJavaSourceMI;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem newViskitProjectMI;
    private javax.swing.JMenuItem openAnotherAnalystReportMI;
    private javax.swing.JMenu runAssemblyMenu;
    private javax.swing.JPanel runAssemblyPanel;
    private javax.swing.JMenuItem saveAnalystReportXml;
    private javax.swing.JMenuItem saveScreenImageMI;
    private javax.swing.JMenuItem settingsMI;
    private javax.swing.JMenuItem tutorialMI;
    private javax.swing.JMenuItem viewAnalystReportXmlMI;
    private javax.swing.JMenuItem viewSavedXmlMI;
    private javax.swing.JMenuBar viskitMenuBar;
    private javax.swing.JTabbedPane viskitTabbedPane;
    private javax.swing.JMenuItem zipMailViskitProjectMI;
    // End of variables declaration//GEN-END:variables
}
