//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.13 at 11:41:18 AM PST 
//


package viskit.xsd.bindings.cli;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Assembly"/&gt;
 *         &lt;element ref="{}EventGraph" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}ExtensionJar" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assembly",
    "eventGraph",
    "extensionJar"
})
@XmlRootElement(name = "Config")
public class Config {

    @XmlElement(name = "Assembly", required = true)
    protected Assembly assembly;
    @XmlElement(name = "EventGraph")
    protected List<EventGraph> eventGraph;
    @XmlElement(name = "ExtensionJar")
    protected List<ExtensionJar> extensionJar;

    /**
     * Gets the value of the assembly property.
     * 
     * @return
     *     possible object is
     *     {@link Assembly }
     *     
     */
    public Assembly getAssembly() {
        return assembly;
    }

    /**
     * Sets the value of the assembly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assembly }
     *     
     */
    public void setAssembly(Assembly value) {
        this.assembly = value;
    }

    /**
     * Gets the value of the eventGraph property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventGraph property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventGraph().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventGraph }
     * 
     * 
     */
    public List<EventGraph> getEventGraph() {
        if (eventGraph == null) {
            eventGraph = new ArrayList<EventGraph>();
        }
        return this.eventGraph;
    }

    /**
     * Gets the value of the extensionJar property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extensionJar property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtensionJar().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionJar }
     * 
     * 
     */
    public List<ExtensionJar> getExtensionJar() {
        if (extensionJar == null) {
            extensionJar = new ArrayList<ExtensionJar>();
        }
        return this.extensionJar;
    }

}
