/*
 * ViskitProjectGenerationDialog3.java
 *
 * Created on August 19, 2008, 2:49 PM
 */
package viskit.view.dialog;

import java.awt.Dialog;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.WindowConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import viskit.ViskitProject;

/** Dialog to assist in generating a new viskit project directory space
 *
 * @author  mike
 * @version $Id$
 */
public class ViskitProjectGenerationDialog3 extends javax.swing.JPanel {

    public static boolean cancelled = true;  // by default
    public static String projectPath = "";
    private static JDialog dialog;

    public static void showDialog() {
        ViskitProjectGenerationDialog3 panel = new ViskitProjectGenerationDialog3();
        dialog = new JDialog((Dialog) null, true);  // modal
        dialog.setTitle("Viskit Project Creation");
        dialog.setContentPane(panel);
        dialog.pack();
        dialog.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE); //WindowConstants.DO_NOTHING_ON_CLOSE);
        // Dialog will appear in center screen
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }

    /** Creates new form ViskitProjectGenerationDialog3 */
    public ViskitProjectGenerationDialog3() {
        initComponents();

        DocumentListener lis = new myDocListener();
        projectNameTF.getDocument().addDocumentListener(lis);
        projectLocationTF.getDocument().addDocumentListener(lis);

        projectNameTF.setText(ViskitProject.DEFAULT_PROJECT_NAME);
        projectLocationTF.setText(ViskitProject.DEFAULT_VISKIT_PROJECTS_DIR);
    }

    class myDocListener implements DocumentListener {

        @Override
        public void changedUpdate(DocumentEvent e) {
            common();
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            common();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            common();
        }
        StringBuffer sb = new StringBuffer();

        private void common() {
            sb.setLength(0);

            sb.append(projectLocationTF.getText().trim());
            int len;
            while ((len = sb.length()) > 0) {
                if (sb.charAt(len - 1) != '/') {
                    break;
                }
                sb.setLength(len - 1);
            }

            sb.append("/");
            sb.append(projectNameTF.getText().trim());
            projectPathTF.setText(sb.toString().replaceAll("\\\\", "/"));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        projectNameLabel = new javax.swing.JLabel();
        projectNameTF = new javax.swing.JTextField();
        projectLocationLabel = new javax.swing.JLabel();
        projectLocationTF = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        projectPathLabel = new javax.swing.JLabel();
        projectPathTF = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        spacerLabel4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new java.awt.GridBagLayout());

        projectNameLabel.setText("Project Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(projectNameLabel, gridBagConstraints);

        projectNameTF.setColumns(30);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(projectNameTF, gridBagConstraints);

        projectLocationLabel.setText("Project Location:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(projectLocationLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(projectLocationTF, gridBagConstraints);

        browseButton.setText("Browse...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(browseButton, gridBagConstraints);

        projectPathLabel.setText("Project Path:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(projectPathLabel, gridBagConstraints);

        projectPathTF.setEditable(false);
        projectPathTF.setBackground(new java.awt.Color(204, 204, 204));
        projectPathTF.setColumns(30);
        projectPathTF.setToolTipText("The path is a combination of the location and name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(projectPathTF, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.setPreferredSize(new java.awt.Dimension(65, 22));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        add(cancelButton, gridBagConstraints);

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        add(createButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weighty = 1.0;
        add(spacerLabel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    cancelled = true;
    dialog.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed

private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
    cancelled = false;
    projectPath = projectPathTF.getText().trim().replaceAll("\\\\", "/");
    dialog.dispose();
}//GEN-LAST:event_createButtonActionPerformed

private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed

    File file = ViskitProject.newProjectPath(this, System.getProperty("user.home"));

    if (file != null) {
        projectLocationTF.setText(file.getAbsolutePath().replaceAll("\\\\", "/"));
    }
}//GEN-LAST:event_browseButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel projectLocationLabel;
    private javax.swing.JTextField projectLocationTF;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectNameTF;
    private javax.swing.JLabel projectPathLabel;
    private javax.swing.JTextField projectPathTF;
    private javax.swing.JLabel spacerLabel4;
    // End of variables declaration//GEN-END:variables
}
