//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.13 at 11:41:18 AM PST 
//


package viskit.xsd.bindings.assembly.stats;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="mean" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0.0" /&gt;
 *       &lt;attribute name="variance" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0.0" /&gt;
 *       &lt;attribute name="standardDeviation" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0.0" /&gt;
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}integer" default="0" /&gt;
 *       &lt;attribute name="minObs" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0.0" /&gt;
 *       &lt;attribute name="maxObs" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0.0" /&gt;
 *       &lt;attribute name="sampleType" default="TALLY"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="TALLY"/&gt;
 *             &lt;enumeration value="TIME_VARYING"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "SampleStatistics")
public class SampleStatistics {

    @XmlAttribute(name = "mean")
    protected BigDecimal mean;
    @XmlAttribute(name = "variance")
    protected BigDecimal variance;
    @XmlAttribute(name = "standardDeviation")
    protected BigDecimal standardDeviation;
    @XmlAttribute(name = "count")
    protected BigInteger count;
    @XmlAttribute(name = "minObs")
    protected BigDecimal minObs;
    @XmlAttribute(name = "maxObs")
    protected BigDecimal maxObs;
    @XmlAttribute(name = "sampleType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sampleType;
    @XmlAttribute(name = "name")
    @XmlSchemaType(name = "anySimpleType")
    protected String name;

    /**
     * Gets the value of the mean property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMean() {
        if (mean == null) {
            return new BigDecimal("0.0");
        } else {
            return mean;
        }
    }

    /**
     * Sets the value of the mean property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMean(BigDecimal value) {
        this.mean = value;
    }

    /**
     * Gets the value of the variance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVariance() {
        if (variance == null) {
            return new BigDecimal("0.0");
        } else {
            return variance;
        }
    }

    /**
     * Sets the value of the variance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVariance(BigDecimal value) {
        this.variance = value;
    }

    /**
     * Gets the value of the standardDeviation property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStandardDeviation() {
        if (standardDeviation == null) {
            return new BigDecimal("0.0");
        } else {
            return standardDeviation;
        }
    }

    /**
     * Sets the value of the standardDeviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStandardDeviation(BigDecimal value) {
        this.standardDeviation = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCount() {
        if (count == null) {
            return new BigInteger("0");
        } else {
            return count;
        }
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCount(BigInteger value) {
        this.count = value;
    }

    /**
     * Gets the value of the minObs property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinObs() {
        if (minObs == null) {
            return new BigDecimal("0.0");
        } else {
            return minObs;
        }
    }

    /**
     * Sets the value of the minObs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinObs(BigDecimal value) {
        this.minObs = value;
    }

    /**
     * Gets the value of the maxObs property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxObs() {
        if (maxObs == null) {
            return new BigDecimal("0.0");
        } else {
            return maxObs;
        }
    }

    /**
     * Sets the value of the maxObs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxObs(BigDecimal value) {
        this.maxObs = value;
    }

    /**
     * Gets the value of the sampleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleType() {
        if (sampleType == null) {
            return "TALLY";
        } else {
            return sampleType;
        }
    }

    /**
     * Sets the value of the sampleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleType(String value) {
        this.sampleType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
